name: sGift
main: me.Sk8r2K10.sGift.sGift
version: 1.0
description: Gift/Trade Items to other Players
softdepend: [Vault]
commands:
  gift:
    description: Gift a Player
  trade:
    description: Trade with a Player

permissions:
    ugift.gift:
        description: Give access to /gift
        default: op
        children:
            ugift.gift.help: true
    ugift.admin:
        description: Give access to Admin commands
        default: op
    ugift.trade:
        description: Give access to /trade
        default: op
        children:
            ugift.trade.help: true