name: sGift
main: me.Sk8r2K10.sGift.sGift
version: 1.2.3
description: Gift/Trade Items to other Players
softdepend: [Vault]
commands:
  gift:
    description: Gift a Player
  trade:
    description: Trade with a Player
  sgift:
    description: Admin commands for sGift

permissions:
    sgift.gift:
        description: Give access to /gift
        default: op
        children:
            sgift.gift.help: true
    sgift.admin:
        description: Give access to Admin commands
        default: op
    sgift.trade:
        description: Give access to /trade
        default: op
        children:
            sgift.trade.help: true
    sgift.set:
        description: Gives access to /sgift set
        default: op
    sgift.halt:
        description: Gives access to /sgift halt
        default: op