name: uGift
main: me.Sk8r2K10.uGift.uGift
version: 1.0
description: Gift/Trade Items to other Players
depend: [Vault]
commands:
  gift:
    description: Gift a Player
  trade:
    description: Trade with a Player

permissions:
    ugift.gift:
        description: Give access to /gift
        default: op
    ugift.admin:
        description: Give access to Admin commands
        default: op
    ugift.help:
        description: Give access to Help commands
        default: op
    ugift.trade:
        description: Give access to /trade
        default: op